BlowOut/Models/Instrument.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace BlowOut.Models
{
    [Table("Instruments")]
    public class Instrument
    {
        [Key]
        public int InstrumentID { get; set; }
        public string Description { get; set; }
        public string Type { get; set; }
        public int Price { get; set; }
        public string PicURL { get; set; }
        public int ClientID { get; set; }
    }
}

BlowOut/Controllers/InstrumentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BlowOut.Models;
using System.Data.Entity;
using BlowOut.DAL;

namespace BlowOut.Controllers
{

    public class InstrumentController : Controller
    {
        private RentalsContext db = new RentalsContext();

        // GET: Instrument
        public ActionResult Trumpet()
        {

            return View();
        }

        public ActionResult NewTrumpet()
        {

            //get new pictures
            //set up instrument in database
            var entity = new Instrument { Description = "Trumpet", PicURL = "~/Content/Images/trumpet2.jpg", Price = 55, Type = "New" };
            db.Instruments.Add(entity);
            db.SaveChanges();

            //go to client method
            return RedirectToAction("Create", "Clients");
        }

        public ActionResult UsedTrumpet()
        {
            //set up instrument in database
            var entity = new Instrument { Description = "Trumpet", PicURL = "~/Content/Images/trumpet2.jpg", Price = 25, Type = "Used" };
            db.Instruments.Add(entity);
            db.SaveChanges();

            //go to client method
            return RedirectToAction("Create", "Clients");
        }

        public ActionResult Tuba()
        {
            return View();
        }

        public ActionResult TubaNew()
        {
            //set up instrument in database
            var entity = new Instrument { Description = "Tuba", PicURL = "~/Content/Images/tuba3.jpg", Price = 70, Type = "New" };
            db.Instruments.Add(entity);
            db.SaveChanges();

            //go to client method
            return RedirectToAction("Create", "Clients");
        }

        public ActionResult TubaUsed()
        {
            //set up instrument in database
            var entity = new Instrument { Description = "Tuba", PicURL = "~/Content/Images/tuba3.jpg", Price = 50, Type = "Used" };
            db.Instruments.Add(entity);
            db.SaveChanges();

            //go to client method
            return RedirectToAction("Create", "Clients");
        }

        public ActionResult Trombone()
        {
            return View();
        }

        public ActionResult TromboneNew()
        {
            //set up instrument in database
            var entity = new Instrument { Description = "Trombone", PicURL = "~/Content/Images/trombone3.jpg", Price = 60, Type = "New" };
            db.Instruments.Add(entity);
            db.SaveChanges();

            //go to client method
            return RedirectToAction("Create", "Clients");
        }

        public ActionResult TromboneUsed()
        {
            //set up instrument in database
            var entity = new Instrument { Description = "Trombone", PicURL = "~/Content/Images/trombone3.jpg", Price = 35, Type = "Used" };
            db.Instruments.Add(entity);
            db.SaveChanges();

            //go to client method
            return RedirectToAction("Create", "Clients");
        }

        public ActionResult Clarinet()
        {
            return View();
        }

        public ActionResult ClarinetNew()
        {
            //set up instrument in database
            var entity = new Instrument { Description = "Clarinet", PicURL = "~/Content/Images/clarinet2.jpg", Price = 35, Type = "New" };
            db.Instruments.Add(entity);
            db.SaveChanges();

            //go to client method
            return RedirectToAction("Create", "Clients");
        }

        public ActionResult ClarinetUsed()
        {
            //set up instrument in database
            var entity = new Instrument { Description = "Clarinet", PicURL = "~/Content/Images/clarinet2.jpg", Price = 27, Type = "Used" };
            db.Instruments.Add(entity);
            db.SaveChanges();

            //go to client method
            return RedirectToAction("Create", "Clients");
        }

        public ActionResult Flute()
        {
            return View();
        }

        public ActionResult FluteNew()
        {
            //set up instrument in database
            var entity = new Instrument { Description = "Flute", PicURL = "~/Content/Images/flute2.jpg", Price = 40, Type = "New" };
            db.Instruments.Add(entity);
            db.SaveChanges();

            //go to client method
            return RedirectToAction("Create", "Clients");
        }

        public ActionResult FluteUsed()
        {
            //set up instrument in database
            var entity = new Instrument { Description = "Flute", PicURL = "~/Content/Images/flute2.jpg", Price = 25, Type = "Used" };
            db.Instruments.Add(entity);
            db.SaveChanges();

            //go to client method
            return RedirectToAction("Create", "Clients");
        }

        public ActionResult Saxophone()
        {
            return View();
        }

        public ActionResult SaxophoneNew()
        {
            //set up instrument in database
            var entity = new Instrument { Description = "Saxophone", PicURL = "~/Content/Images/saxophone2.jpg", Price = 42, Type = "New" };
            db.Instruments.Add(entity);
            db.SaveChanges();

            //go to client method
            return RedirectToAction("Create", "Clients");
        }

        public ActionResult SaxophoneUsed()
        {
            //set up instrument in database
            var entity = new Instrument { Description = "Saxophone", PicURL = "~/Content/Images/saxophone2.jpg", Price = 30, Type = "Used" };
            db.Instruments.Add(entity);
            db.SaveChanges();

            //go to client method
            return RedirectToAction("Create", "Clients");
        }
    }
}

BlowOut/Views/Instrument/Clarinet.cshtml
@{
    ViewBag.Title = "Clarinet";
}
<body class="backgroundImage">
    <h2>Clever Clarinets</h2>

    <div class="jumbotron">

        <h3>@ViewBag.PriceInfo</h3>
        <center>
            <h4>New: $35/month</h4>
            <h4>Used: $27/month</h4>
            <img src="~/Content/Images/clarinet.jpg" class="myInstImage" /><br /><br />
            <input value="New" type="button" class="btn btn-primary" onclick="location.href='@Url.Action("ClarinetNew", "Instrument")'" />
            <input value="Used" type="button" class="btn btn-primary" onclick="location.href='@Url.Action("ClarinetUsed", "Instrument")'" />
            <br /><br />
            
        </center>
        <p class="text-muted">
            <ul class="text-muted">
                <li>Once the <strong>18 months</strong> has been achieved, you will own the instrument. </li>
                <li>If you return it at any time before 3 months there will be a <strong>$200</strong> re-stocking fee. </li>
                <li>If you return it after 3 months you <string>forfeit any</string> any equity in the instrument.</li>
            </ul>
        </p>
    </div>

</body>

BlowOut/Views/Instrument/Flute.cshtml
@{
    ViewBag.Title = "Flute";
}

<h2>Flirty Flutes</h2>
<body class="backgroundImage">
    <div class="jumbotron">
        <center>
            <h4>New: $40/month</h4>
            <h4>Used: $25/month</h4>
            <img src="~/Content/Images/flute.jpg" class="myInstImage"/><br /><br />
            <input value="New" type="button" class="btn btn-primary" onclick="location.href='@Url.Action("FluteNew", "Instrument")'" />
            <input value="Used" type="button" class="btn btn-primary" onclick="location.href='@Url.Action("FluteUsed", "Instrument")'" />
            <br /><br />
            <h3>@ViewBag.PriceInfo</h3>
        </center>
        
        <p class="text-muted">
            <ul class="text-muted">
                <li>Once the <strong>18 months</strong> has been achieved, you will own the instrument. </li>
                <li>If you return it at any time before 3 months there will be a <strong>$200</strong> re-stocking fee. </li>
                <li>If you return it after 3 months you <string>forfeit any</string> any equity in the instrument.</li>
            </ul>
        </p>
    </div>
    
</body>

BlowOut/Views/Instrument/Saxophone.cshtml
@{
    ViewBag.Title = "Saxophone";
}

<h2>Suave Saxophones</h2>

<body class="backgroundImage">
    <div class="jumbotron">
        <center>
            <h4>New: $42/month</h4>
            <h4>Used: $30/month</h4>
            <img src="~/Content/Images/sax2.jpg" class="myInstImage" /><br /><br />
            <input value="New" type="button" class="btn btn-primary" onclick="location.href='@Url.Action("SaxophoneNew", "Instrument")'" />
            <input value="Used" type="button" class="btn btn-primary" onclick="location.href='@Url.Action("SaxophoneUsed", "Instrument")'" />
        </center>
        
        <br /><br />
        <h3>@ViewBag.PriceInfo</h3>
        <p class="text-muted">
            <ul class="text-muted">
                <li>Once the <strong>18 months</strong> has been achieved, you will own the instrument. </li>
                <li>If you return it at any time before 3 months there will be a <strong>$200</strong> re-stocking fee. </li>
                <li>If you return it after 3 months you <string>forfeit any</string> any equity in the instrument.</li>
            </ul>
        </p>
    </div>
    
</body>

BlowOut/Views/Instrument/Trombone.cshtml
@{
    ViewBag.Title = "Trombone";
}

<h2>Terrific Trombones</h2>

<body class="backgroundImage">
    <div class="jumbotron">
        <center>
            <h4>New: $60/month</h4>
            <h4>Used: $35/month</h4>
            <img src="~/Content/Images/trombone2.jpg" class="myInstImage" /><br /><br />
            <input value="New" type="button" class="btn btn-primary" onclick="location.href='@Url.Action("TromboneNew", "Instrument")'" />
            <input value="Used" type="button" class="btn btn-primary" onclick="location.href='@Url.Action("TromboneUsed", "Instrument")'" />
            <br /><br />
        </center>
        
        <h3>@ViewBag.PriceInfo</h3>
        <p class="text-muted">
            <ul class="text-muted">
                <li>Once the <strong>18 months</strong> has been achieved, you will own the instrument. </li>
                <li>If you return it at any time before 3 months there will be a <strong>$200</strong> re-stocking fee. </li>
                <li>If you return it after 3 months you <string>forfeit any</string> any equity in the instrument.</li>
            </ul>
        </p>
    </div>
    
</body>

BlowOut/Views/Instrument/Trumpet.cshtml
@{
    ViewBag.Title = "Trumpet";
}

<h2>Tenacious Trumpets</h2>

<body class="backgroundImage">
    <div class="jumbotron">
        <center>
            <h4>New: $55/month</h4>
            <h4>Used: $25/month</h4>
            <img src="~/Content/Images/trumpet.jpg" class="myInstImage"/><br /><br />
            <input value="New" type="button" class="btn btn-primary" onclick="location.href='@Url.Action("NewTrumpet", "Instrument")'" />
            <input value="Used" type="button" class="btn btn-primary" onclick="location.href='@Url.Action("UsedTrumpet", "Instrument")'" />
            <br /><br />
        </center>
        
        <h3>@ViewBag.PriceInfo</h3>
        <p class="text-muted">
            <ul class="text-muted">
                <li>Once the <strong>18 months</strong> has been achieved, you will own the instrument. </li>
                <li>If you return it at any time before 3 months there will be a <strong>$200</strong> re-stocking fee. </li>
                <li>If you return it after 3 months you <string>forfeit any</string> any equity in the instrument.</li>
            </ul>
        </p>
    </div>
    
</body>

BlowOut/Views/Instrument/Tuba.cshtml
@{
    ViewBag.Title = "Tuba";
}

<h2>Tremendous Tubas</h2>

<body class="backgroundImage">
    <div class="jumbotron">
        <center>
            <h4>New: $70/month</h4>
            <h4>Used: $50/month</h4>
            <img src="~/Content/Images/tuba2.PNG" class="myInstImage" /><br /><br />
            <input value="New" type="button" class="btn btn-primary" onclick="location.href='@Url.Action("TubaNew", "Instrument")'" />
            <input value="Used" type="button" class="btn btn-primary" onclick="location.href='@Url.Action("TubaUsed", "Instrument")'" />
            <br /><br />
        </center>
        
        <h3>@ViewBag.PriceInfo</h3>
        <p class="text-muted">
            <ul class="text-muted">
                <li>Once the <strong>18 months</strong> has been achieved, you will own the instrument. </li>
                <li>If you return it at any time before 3 months there will be a <strong>$200</strong> re-stocking fee. </li>
                <li>If you return it after 3 months you <string>forfeit any</string> any equity in the instrument.</li>
            </ul>
        </p>
    </div>
    
</body>